development:
  adapter: postgresql
  database: portfolio
  user: portfolio
  password: <%= ENV["DB_PWD"] %> 
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  host: localhost

production:
  adapter: postgresql
  database: portfolio
  user:    portfolio 
  password: <%= ENV["DB_PWD"] %>
  host: localhost
