development:
  adapter: postgresql
  database: portfolio
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  host: localhost

production:
  adapter: postgresql
  database: portfolio
  host: localhost





