development:
  adapter: postgresql
  database: portfolio
  user:    portfolio 
  password: 0$car5fish
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000




